### ISSUE TITLE
授人以渔，readme是不是太简洁了点？代码里面注释太少了，看的云里雾里。

### ISSUE THREAD

**Issue by chencmgithub** [hiisea/elux#18]

**Comment by hiisea** [comment]
兄台用的哪个工程模板？可以加下我微信ks8864

**Comment by hiisea** [comment]
官网文档有看一下么https://eluxjs.com，然后加微信交流群吧..！

**Comment by chencmgithub** [comment]
嗯，貌似没有微信群，官网也看了， 大佬的思路我比较赞同，想跟你取取经，看看怎么应用到项目中去。
我们主要是做实施项目的，恰恰微模块比较贴切我们的实际情况，项目中我们其实也是这么去规划的，但是没有形成框架，统一思想。

**Comment by hiisea** [comment]
> 嗯，貌似没有微信群，官网也看了， 大佬的思路我比较赞同，想跟你取取经，看看怎么应用到项目中去。 我们主要是做实施项目的，恰恰微模块比较贴切我们的实际情况，项目中我们其实也是这么去规划的，但是没有形成框架，统一思想。

取经不敢说，欢迎一起交流探索，加我微信ks8864

**Comment by hiisea** [comment]
完善文档
