### ISSUE TITLE
异步Render的情况下，onMount方法返回Promise对象。第二次点击菜单时，发生了异常。

### ISSUE THREAD

**Issue by soonboylena** [hiisea/elux#19]
前提：
在OnMount方法中，返回一个Promise对象：
![图片](https://user-images.githubusercontent.com/16619932/197668122-2c536d96-2e2e-44b9-8b0d-94e6661cb22a.png)

现象：
第一次通过左侧菜单点击进入时，正常。
再次点击时左侧菜单时，发生异常。

![图片](https://user-images.githubusercontent.com/16619932/197668365-277e4c6d-719e-4993-beee-8eb54b0eb477.png)

期望结果：
能够正常显示画面。

**Comment by hiisea** [comment]
收到！正在检查！

**Comment by soonboylena** [comment]
感谢 @hiisea  这么快给予解决。

解决方法：升级 @elux/react-web 版本 到 2.6.3
![图片](https://user-images.githubusercontent.com/16619932/197688064-014b1c61-f8c7-414c-ad02-ff22be529052.png)
