### ISSUE TITLE
有示例项目学习下吗

### ISSUE THREAD

**Issue by sixinyiyu** [hiisea/elux#8]
支持vite？

**Comment by hiisea** [comment]
亲，cli工程模版附带一个增删改查的实例，如果你不想全局安装cli，可以一行代码搞定：npx @elux/cli-init elux-init

**Comment by hiisea** [comment]
> 支持vite？

暂时不支持vite，用的webpack，可以自由修改webpack配置

**Comment by chinaliuming123** [comment]
运行 npx @elux/cli-init elux-init 选择vue3模板，下载下来的却是react的项目

**Comment by chinaliuming123** [comment]
gitee源，微前端+微模块，vue3

**Comment by chinaliuming123** [comment]
貌似全都是react模板

**Comment by chinaliuming123** [comment]
粗心了，我把tsx默认想成react了，原来是vue3+tsx，大佬牛皮

**Comment by hiisea** [comment]
> 粗心了，我把tsx默认想成react了，原来是vue3+tsx，大佬牛皮

哈，因为方便与React工程对比，所以用的tsx，其实也可以使用template，但是template的TS提示没那么友好，还需要安装volar扩展...

**Comment by sixinyiyu** [comment]
cli工程学习了，unocss 搭配咋使用？

**Comment by hiisea** [comment]
> cli工程学习了，unocss 搭配咋使用, vue的模板 install后unplugin-auto-import 这些都直接使用即可 ？

Elux基于webpack配置，打开./elux.config.js

```js
module.exports = {
  all: {
    //增加以下webpackConfig的自定义回调方法
    webpackConfigTransform(config) {
      //这里可以自由修改webpack配置
      console.log(config.plugins);
      config.plugins.unshift(UnoCSS(....)) //具体在webpack怎么配置UNOCSS百度一下吧
      return config;
    },
  },
```
我没用过UNOCSS，百度一下怎么在webpack中配置UNOCSS吧，有问题加QQ群即时沟通

**Comment by hiisea** [comment]
> 建议使用`elux.config.ts`，再配合 defineConfig 之类的封装方法，让配置拥有提示

感谢建议，加入了Feature，待开发...

**Comment by hiisea** [comment]
> 支持vite？

准备等vite3正式发布后接入vite

**Comment by sixinyiyu** [comment]
> 

vite3 发布段时间拉

**Comment by hiisea** [comment]
> > 
> 
> vite3 发布段时间拉

注意到了，让子弹再飞一会吧😄

**Comment by chencmgithub** [comment]
掘金里面看到的，围观学习一下

**Comment by sixinyiyu** [comment]
再来问问 支持vite3了吗

**Comment by hiisea** [comment]
> 再来问问 支持vite3了吗

亲，还没哦。。
